language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_4.1.gemfile

script: bundle exec rspec spec
